# -*- coding: utf-8 -*-
"""sales analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIIhQik1Gup9dPe8AbHMkZu1NfEHvvPE
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv
from collections import defaultdict

# Store user credentials dynamically
USER_CREDENTIALS = {}

# Set up new user credentials
def setup_new_user():
    print("No users found. Please create your first login credentials.")
    username = input("Create Username: ")
    password = input("Create Password: ")
    USER_CREDENTIALS[username] = password
    print(f"\nAccount created successfully! Welcome, {username}.\n")
    return True

# Add multiple users
def add_user():
    print("\nAdd a New User")
    username = input("Enter Username: ")
    if username in USER_CREDENTIALS:
        print("This username already exists.")
        return
    password = input("Enter Password: ")
    USER_CREDENTIALS[username] = password
    print(f"\nUser {username} added successfully.\n")

# Authenticate user with username and password
def authenticate_user():
    if not USER_CREDENTIALS:
        return setup_new_user()  # Creates a new user and returns True
    else:
        while True:
            print("Please log in to access the sales analysis system.")
            username = input("Username: ")
            password = input("Password: ")

            if USER_CREDENTIALS.get(username) == password:
                print(f"\nWelcome, {username}!")
                return True  # Successful login
            else:
                print("\nInvalid username or password. Please try again.")

# Load product data from CSV
def load_product_data(file_path):
    try:
        data = []
        with open(file_path, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                data.append(row)
        return data
    except FileNotFoundError:
        print("Error: The specified file was not found.")
        return None

# Display Product Data
def display_product_data(data):
    print("\nProduct Sales Report (Days 1 to 30):")
    for row in data:
        print(f"{row['Item']: <20} | {', '.join([f'{k}: {v}' for k, v in row.items() if 'Day' in k])}")

# Calculate Total Sales
def calculate_total_sales(data):
    total_sales = 0
    for row in data:
        price = float(row['Price'])
        for day in range(1, 31):
            day_key = f'Day{day}'
            total_sales += price * int(row[day_key])
    return total_sales

# Calculate Daily Totals, Averages, and Profit/Loss
def calculate_daily_stats(data):
    daily_totals = np.zeros(30)
    prices = []

    for row in data:
        price = float(row['Price'])
        prices.append(price)
        for day in range(30):
            day_key = f'Day{day+1}'
            daily_totals[day] += price * int(row[day_key])

    daily_averages = daily_totals.mean()
    profit_loss = np.diff(daily_totals)
    return daily_totals, daily_averages, profit_loss

# Visualize Daily Sales Trend
def plot_daily_sales(daily_totals):
    plt.figure(figsize=(10, 5))
    plt.plot(range(1, 31), daily_totals, marker='o', color='b', label='Daily Total Sales')
    plt.xlabel('Day')
    plt.ylabel('Total Sales (₹)')
    plt.title('Daily Sales Trend Over 30 Days')
    plt.legend()
    plt.show()

# Bar Graph of Daily Sales using Seaborn
def plot_bar_daily_sales(daily_totals):
    plt.figure(figsize=(12, 6))
    sns.barplot(x=np.arange(1, 31), y=daily_totals, palette="viridis")
    plt.xlabel('Day')
    plt.ylabel('Total Sales (₹)')
    plt.title('Daily Sales Bar Graph Over 30 Days')
    plt.show()

# Option to Find Most and Least Selling Days
def find_extreme_days(daily_totals):
    most_selling_day = np.argmax(daily_totals) + 1
    least_selling_day = np.argmin(daily_totals) + 1
    return most_selling_day, least_selling_day

# Find Most Sold Items by Category
def find_most_sold_items(data):
    categories = defaultdict(list)
    for row in data:
        categories[row['Category']].append(row)

    most_sold_items = {}
    for category, items in categories.items():
        sales_amount = np.zeros(len(items))
        for idx, item in enumerate(items):
            price = float(item['Price'])
            sales_amount[idx] = sum(price * int(item[f'Day{day+1}']) for day in range(30))
        most_sold_item = items[np.argmax(sales_amount)]['Item']
        most_sold_items[category] = most_sold_item

    return most_sold_items

# Inventory Analysis
def calculate_inventory(data, initial_stock):
    remaining_stock = []
    for row in data:
        total_sold = sum(int(row[f'Day{day+1}']) for day in range(30))
        remaining_stock.append({'Item': row['Item'], 'Remaining Stock': initial_stock - total_sold})
    return remaining_stock

# Sales Forecasting (Simple Moving Average)
def sales_forecasting(daily_totals, window_size=3):
    rolling_avg = np.convolve(daily_totals, np.ones(window_size)/window_size, mode='valid')
    forecast = rolling_avg[-1]
    print(f"\nSales Forecast (next day, based on {window_size}-day moving average): ₹{forecast:.2f}")
    return forecast

# Profitability Analysis
def profitability_analysis(data, cost_price_percentage=0.6):
    total_sales_value = 0
    total_cost = 0
    for row in data:
        price = float(row['Price'])
        cost_price = price * cost_price_percentage
        for day in range(30):
            day_key = f'Day{day+1}'
            quantity_sold = int(row[day_key])
            total_sales_value += price * quantity_sold
            total_cost += cost_price * quantity_sold

    profit = total_sales_value - total_cost
    profit_margin = (profit / total_sales_value) * 100
    print(f"\nTotal Profit: ₹{profit:.2f}")
    print(f"Profit Margin: {profit_margin:.2f}%")
    return profit, profit_margin

# Category Sales Analysis
def category_sales_analysis(data):
    category_totals = defaultdict(float)
    for row in data:
        price = float(row['Price'])
        for day in range(30):
            day_key = f'Day{day+1}'
            category_totals[row['Category']] += price * int(row[day_key])

    print("\nCategory Sales Analysis:")
    for category, total in category_totals.items():
        print(f"{category}: ₹{total}")
    return category_totals

def main():
    while True:
        if not authenticate_user():
            continue  # If authentication fails, prompt again

        # Load data from CSV
        data = load_product_data('product_sales.csv')
        if data is None:
            return  # Exit if data could not be loaded

        initial_stock = 500  # Assuming each product starts with 500 units

        # User Options
        while True:
            print("\nOptions:")
            print("1. Display Product Data")
            print("2. Calculate Total Sales")
            print("3. Show Daily Sales Trend")
            print("4. Find Most and Least Selling Days")
            print("5. Find Most Sold Items by Category")
            print("6. Calculate Inventory Levels")
            print("7. Sales Forecasting")
            print("8. Profitability Analysis")
            print("9. Category Sales Analysis")
            print("10. Show Daily Sales Bar Graph")
            print("11. Add New User")
            print("12. Log Out")
            print("0. Exit")
            choice = input("Select an option: ")

            if choice == "1":
                display_product_data(data)
            elif choice == "2":
                total_sales = calculate_total_sales(data)
                print(f"\nTotal Sales: ₹{total_sales}")
            elif choice == "3":
                daily_totals, _, _ = calculate_daily_stats(data)
                plot_daily_sales(daily_totals)
            elif choice == "4":
                daily_totals, _, _ = calculate_daily_stats(data)
                most_selling_day, least_selling_day = find_extreme_days(daily_totals)
                print(f"\nMost Selling Day: Day {most_selling_day}")
                print(f"Least Selling Day: Day {least_selling_day}")
            elif choice == "5":
                most_sold_items = find_most_sold_items(data)
                print("\nMost Sold Items by Category:")
                for category, item in most_sold_items.items():
                    print(f"{category}: {item}")
            elif choice == "6":
                inventory = calculate_inventory(data, initial_stock)
                print("\nInventory Levels:")
                for item in inventory:
                    print(f"{item['Item']}: {item['Remaining Stock']}")
            elif choice == "7":
                daily_totals, _, _ = calculate_daily_stats(data)
                sales_forecasting(daily_totals)
            elif choice == "8":
                profitability_analysis(data)
            elif choice == "9":
                category_sales_analysis(data)
            elif choice == "10":
                daily_totals, _, _ = calculate_daily_stats(data)
                plot_bar_daily_sales(daily_totals)
            elif choice == "11":
                add_user()  # Add a new user
            elif choice == "12":
                break  # Log out and prompt to re-authenticate
            elif choice == "0":
                print("Exiting system...")
                return  # Exit the entire system
            else:
                print("Invalid option. Please try again.")

if __name__ == "__main__":
    main()